
CONFIG_DRM_MSM            := y
CONFIG_DRM_MSM_DSI        := y
CONFIG_DSI_PARSER         := y
CONFIG_QCOM_MDSS_PLL      := y
CONFIG_DRM_MSM_REGISTER_LOGGING := y
CONFIG_DISPLAY_BUILD      := m
CONFIG_DRM_MSM_SDE	  := y
CONFIG_DRM_SDE_WB	  := y
CONFIG_DRM_MSM_DP	  := y
CONFIG_DRM_MSM_HDMI	  := y
CONFIG_MDSS_HFI		  := y
